"""initial schema (simulation_cache, simulation_patterns, reuse_metrics)

Revision ID: 72095b7dd318
Revises: 
Create Date: 2026-07-15 17:10:55.326469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72095b7dd318'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reuse_metrics',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('simulation_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('problem_text', sa.Text(), nullable=False),
    sa.Column('simulation_id', sa.String(length=80), nullable=False),
    sa.Column('envelope_json', sa.Text(), nullable=False),
    sa.Column('dsl_version', sa.String(length=16), nullable=False),
    sa.Column('policy_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_cache_key'), ['key'], unique=True)

    op.create_table('simulation_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pattern_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('signature_json', sa.Text(), nullable=False),
    sa.Column('scene_mode', sa.String(length=16), nullable=False),
    sa.Column('semantic_roles', sa.String(length=200), nullable=False),
    sa.Column('template_json', sa.Text(), nullable=False),
    sa.Column('parameter_schema_json', sa.Text(), nullable=False),
    sa.Column('dsl_version', sa.String(length=16), nullable=False),
    sa.Column('policy_version', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_patterns_pattern_key'), ['pattern_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_simulation_patterns_scene_mode'), ['scene_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulation_patterns_semantic_roles'), ['semantic_roles'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_patterns_semantic_roles'))
        batch_op.drop_index(batch_op.f('ix_simulation_patterns_scene_mode'))
        batch_op.drop_index(batch_op.f('ix_simulation_patterns_pattern_key'))

    op.drop_table('simulation_patterns')
    with op.batch_alter_table('simulation_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_cache_key'))

    op.drop_table('simulation_cache')
    op.drop_table('reuse_metrics')
    # ### end Alembic commands ###
